services:
  kafka:
    image: lensesio/fast-data-dev
    container_name: kafka-aio
    environment:
      ADV_HOST: host.docker.internal
      RUNTESTS: "0"
      SAMPLEDATA: "0"
      RUNNING_SAMPLEDATA: "0"
      DISABLE_JMX: "1"
      BROWSECONFIGS: "1"
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://host.docker.internal:8081
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - kafka
    ports:
      - "2181:2181"
      - "3030:3030"
      - "8081-8083:8081-8083"
      - "9092:9092"

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    depends_on:
      - kafka
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_NAME: demo
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://kafka:8081
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - kafka
    ports:
      - "9080:8080"
